# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2ff24913d6d89792234763f0830c676"
name = "SynqSell"
handle = "synqsell"
application_url = "https://zshops-ecology-eminem-auctions.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-3fe7f8c3.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_inventory,read_orders,read_products,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_fulfillments,write_inventory,write_orders,write_products"

[auth]
redirect_urls = [
  "https://zshops-ecology-eminem-auctions.trycloudflare.com/auth/callback",
  "https://zshops-ecology-eminem-auctions.trycloudflare.com/auth/shopify/callback",
  "https://zshops-ecology-eminem-auctions.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "bulk_operations/finish",
  "products/update"
]
  uri = "/webhooks"

[pos]
embedded = false
